version: "3.8"

services:


  leaf:
    build: vxlanrouter
    container_name: leaf
    hostname: leaf
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    privileged: true
    command: /bin/bash /etc/frr/run-frr.sh
    volumes:
      - ${PWD}/r1:/etc/frr
    networks:
      wan1:
        ipv4_address: 10.1.1.21
        ipv6_address: 10:1:1::21

  daas:
    build: vxlanrouter
    container_name: daas
    hostname: daas
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    privileged: true
    command: /bin/bash /etc/frr/run-frr.sh
    volumes:
      - ${PWD}/r2:/etc/frr
    networks:
      wan1:
        ipv4_address: 10.1.1.22
        ipv6_address: 10:1:1::22




  pg:
    build: host
    container_name: pg
    hostname: pg
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    privileged: true
    network_mode: none
    command: /bin/bash /config/network-init.sh
    volumes:
      - ${PWD}/host11:/config

  rpd:
    build: host
    container_name: rpd
    hostname: rpd
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    privileged: true
    network_mode: none
    command: /bin/bash /config/network-init.sh
    volumes:
      - ${PWD}/host21:/config





networks:
  wan1:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
        - subnet: 10:1:1::/64
